# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 14:54
from __future__ import unicode_literals

import baihe_api.common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiheForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '表单',
                'verbose_name_plural': '表单',
            },
        ),
        migrations.CreateModel(
            name='BaiheFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.BaiheForm', verbose_name='表单')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '表单数据',
                'verbose_name_plural': '表单数据',
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '字段类型',
                'verbose_name_plural': '字段类型',
            },
        ),
        migrations.CreateModel(
            name='FormDataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('textarea', models.TextField(blank=True, null=True)),
                ('phone', baihe_api.common.models.PhoneField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('single_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('multiple_choice', baihe_api.common.models.ListField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='排序')),
                ('label_name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('placeholder', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='占位显示')),
                ('choices', models.CharField(blank=True, max_length=100, null=True, verbose_name='选项')),
                ('default', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='默认值')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.FieldType', verbose_name='字段类型')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form_builder.BaiheForm', verbose_name='表单')),
            ],
            options={
                'verbose_name': '表单字段',
                'verbose_name_plural': '表单字段',
            },
        ),
        migrations.AddField(
            model_name='formdatavalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='form_builder.FormField', verbose_name='字段'),
        ),
        migrations.AddField(
            model_name='formdatavalue',
            name='form_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='form_builder.BaiheFormData', verbose_name='表单数据'),
        ),
    ]
