# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
